### PR TITLE
Add Termux support

### PR DESCRIPTION
**Pull request by gergelypolonkai**
Signed-off-by: Gergely Polonkai gergely@polonkai.eu

### CODE REVIEW

**Comment by jwiegley** [comment]
@gergelypolonkai Hi, would you be willing to assign the copyright for these changes to the FSF?  If so, please send an e-mail to assign@gnu.org asking for the required papers.

**Comment by gergelypolonkai** [comment]
Of course, that's one of the reasons I sign off my commits (usually). I'll
mail GNU tomorrow about this one.

**Comment by gergelypolonkai** [comment]
I already have the paper signed and just sent it back to FSF/GNU to be signed on their behalf.

**Review by jwiegley — APPROVED** [review]

**Comment by gergelypolonkai** [comment]
@jwiegley thanks for notifying me, i resolved everything.

**Comment by jwiegley** [comment]
Thank you! Is merged. :) Much appreciation for your patience.

**Pull request merged**
