### PR TITLE
add support for growl on windows

### PR DESCRIPTION
**Pull request by tkhoa2711**

### CODE REVIEW

**Comment by jwiegley** [comment]
Is appending `.exe` really needed for `executable-find` on Windows?

**Comment by jwiegley** [comment]
My other question before accepting this is: Have you signed a copyright assignment with the FSF for these changes?

**Comment by tkhoa2711** [comment]
Well, on Windows there are `growlnotify.com` and `grownotify.exe` (they're described here http://www.growlforwindows.com/gfw/help/growlnotify.aspx). `growlnotify.com` will not work on GUI application.

Even though `(executable-find "growlnotify")` will return `growlnotify.exe` because `.exe` precedes `.com` in `exec-suffixes` list, I think it's better to explicitly state the extension.

Anyway, I use Windows at work so I had the chance to test this out.

**Comment by tkhoa2711** [comment]
Regarding your other question, I've never done that before. How do I do that?

**Comment by jwiegley** [comment]
If just `(executable-find "growlnotify")` works on both Windows and non-Windows, then I would rather just use that, than to conditionalize the code simply for "clarity" on one platform.

To assign copyright, you would send an e-mail to `assign@gnu.org`, asking for the necessary forms.  Since `alert.el` is going to become part of Emacs itself at some point, I need for all contributions to have signed such forms before accepting the pull request.  Thanks!

**Comment by myuhe** [comment]
you can use growl for Windows already.
growl for Windows supports gntp protocol.
https://github.com/jwiegley/alert/blame/master/README.md#L103

**Comment by tkhoa2711** [comment]
@jwiegley I made the change to simplify that search for `growlnotify`. In the meantime, I've asked the GNU guys for necessary copyright papers.

@myuhe I tried to use gntp, but it didn't work out well. Not sure there's anything wrong with my setup, either  with `alert.el` or `Growl` on Windows, or not.

**Comment by myuhe** [comment]
gntp.el requires some setup.
See README.
https://github.com/tekai/gntp.el

I use growl for Windows with gntp.el.

**Comment by jwiegley** [comment]
@tkhoa2711 Hi Khoa, did your assignment papers go through?

**Comment by tkhoa2711** [comment]
@jwiegley I know it's been a long time ago, but I did sign and send the paperwork to GNU back then. I haven't heard confirmation from them though.

**Comment by jwiegley** [comment]
That's good enough for me. If it becomes an issue in future, I'll reach out.

**Pull request merged**
